// This file is generated by update-version.ps1 
 
using System.Reflection;
 
[assembly: AssemblyVersion("dcefc2ee33881a17fec991e2cfef0853a33e50cc")]
[assembly: AssemblyInformationalVersion("dcefc2e")]
