// This file is generated by update-version.ps1 
 
using System.Reflection;
 
[assembly: AssemblyVersion("896aaeb4bf9ab5bf58bc1d09d919e4d5c4115567")]
[assembly: AssemblyInformationalVersion("896aaeb")]
