// This file is generated by update-version.ps1 
 
using System.Reflection;
 
[assembly: AssemblyVersion("a3460c6bae3254c64c090b176aba14f51f3121ef")]
[assembly: AssemblyInformationalVersion("a3460c6")]
